name: tap_eat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.3.0
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  url_launcher: ^6.1.5
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  geolocator: ^11.0.0
  introduction_screen: ^3.1.8
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/tapeaticon.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/images/tapeaticon.png
    - assets/images/logo.png
    - .env

